"""One-shot generator: expand playtest card set to 24 King + 30 Noble designs."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KING = ROOT / "cards" / "king_deck"
NOBLE = ROOT / "cards" / "noble_deck"

NEW_KING = [
    {
        "id": "king_tax_levy_001",
        "name": "Tax Levy",
        "owner_type": "king",
        "category": "economy",
        "rarity": "common",
        "copies_in_deck": 3,
        "timing": "on_reveal",
        "effect": {"primitive": "gold_gain", "params": {"target": "self", "amount": 80}},
        "tags": ["economy"],
        "flavor_text": "The crown's share comes due.",
    },
    {
        "id": "king_crown_tribute_001",
        "name": "Crown Tribute",
        "owner_type": "king",
        "category": "economy",
        "rarity": "common",
        "copies_in_deck": 3,
        "timing": "on_reveal",
        "effect": {
            "primitive": "gold_transfer",
            "params": {"from": "target", "to": "self", "amount": 100},
        },
        "tags": ["economy"],
        "flavor_text": "Every house pays the throne.",
    },
    {
        "id": "king_treasury_dividend_001",
        "name": "Treasury Dividend",
        "owner_type": "king",
        "category": "economy",
        "rarity": "rare",
        "copies_in_deck": 2,
        "timing": "end_of_round",
        "effect": {"primitive": "gold_gain", "params": {"target": "self", "amount": 120}},
        "tags": ["economy"],
        "flavor_text": "A well-fed treasury feeds the crown.",
    },
    {
        "id": "king_royal_alliance_pact_001",
        "name": "Royal Alliance Pact",
        "owner_type": "king",
        "category": "alliance",
        "rarity": "common",
        "copies_in_deck": 3,
        "timing": "on_reveal",
        "effect": {
            "primitive": "alliance_bonus",
            "params": {"amount": 60, "players": ["self", "target"]},
        },
        "tags": ["alliance"],
        "synergy_tags": ["king_alliance"],
        "flavor_text": "Loyalty rewarded — if it holds.",
    },
    {
        "id": "king_crown_betrayal_001",
        "name": "Crown Betrayal",
        "owner_type": "king",
        "category": "betrayal",
        "rarity": "rare",
        "copies_in_deck": 2,
        "timing": "on_reveal",
        "effect": {
            "primitive": "gold_transfer",
            "params": {"from": "target", "to": "self", "amount": 150, "as_theft": True},
            "secondary_effect": {
                "primitive": "mark_status",
                "params": {"target": "self", "status_name": "oathbreaker", "duration_rounds": 2},
            },
        },
        "requires_state": {"alliance_declared_with_target": True},
        "tags": ["betrayal"],
        "flavor_text": "Even kings break promises.",
    },
    {
        "id": "king_false_summons_001",
        "name": "False Summons",
        "owner_type": "king",
        "category": "betrayal",
        "rarity": "common",
        "copies_in_deck": 2,
        "timing": "on_reveal",
        "effect": {
            "primitive": "gold_transfer",
            "params": {"from": "target", "to": "self", "amount": 75, "as_theft": True},
        },
        "tags": ["betrayal"],
        "flavor_text": "Come to court — and leave your purse.",
    },
    {
        "id": "king_royal_decree_001",
        "name": "Royal Decree",
        "owner_type": "king",
        "category": "disruption",
        "rarity": "common",
        "copies_in_deck": 3,
        "timing": "on_reveal",
        "effect": {
            "primitive": "force_discard",
            "params": {"target": "target", "count": 1},
        },
        "tags": ["disruption"],
        "flavor_text": "By order of the crown, discard your plans.",
    },
    {
        "id": "king_sealed_warrant_001",
        "name": "Sealed Warrant",
        "owner_type": "king",
        "category": "disruption",
        "rarity": "rare",
        "copies_in_deck": 2,
        "timing": "on_reveal",
        "effect": {
            "primitive": "force_discard",
            "params": {"target": "target", "count": 2},
        },
        "tags": ["disruption"],
        "flavor_text": "Signed, sealed, confiscated.",
    },
    {
        "id": "king_noble_containment_001",
        "name": "Noble Containment",
        "owner_type": "king",
        "category": "disruption",
        "rarity": "common",
        "copies_in_deck": 2,
        "timing": "on_reveal",
        "effect": {
            "primitive": "skip_next_play",
            "params": {"target": "target"},
        },
        "tags": ["disruption"],
        "flavor_text": "Sit down. You have said enough.",
    },
    {
        "id": "king_iron_curtain_001",
        "name": "Iron Curtain",
        "owner_type": "king",
        "category": "protection",
        "rarity": "common",
        "copies_in_deck": 3,
        "timing": "reactive",
        "effect": {
            "primitive": "protect_gold",
            "params": {
                "target": "self",
                "amount": 120,
                "duration_rounds": 1,
                "specificity": "generic",
                "trigger": {"type": "attacked_this_phase", "target": "self", "attack_type": "gold_theft"},
            },
        },
        "on_whiff_penalty": {
            "primitive": "gold_loss",
            "params": {"target": "self", "amount": 30},
        },
        "tags": ["protection"],
        "synergy_tags": ["king_defense"],
        "flavor_text": "The treasury closes its gates.",
    },
    {
        "id": "king_customs_seal_001",
        "name": "Customs Seal",
        "owner_type": "king",
        "category": "protection",
        "rarity": "rare",
        "copies_in_deck": 2,
        "timing": "reactive",
        "effect": {
            "primitive": "protect_gold",
            "params": {
                "target": "self",
                "amount": 200,
                "duration_rounds": 1,
                "specificity": "targeted",
                "targeted_attacker": 0,
                "trigger": {"type": "attacker_is", "seat": 0},
            },
        },
        "on_whiff_penalty": {
            "primitive": "gold_loss",
            "params": {"target": "self", "amount": 50},
        },
        "tags": ["protection"],
        "flavor_text": "Wrong thief, wrong day — or wrong guess.",
    },
    {
        "id": "king_diplomatic_immunity_001",
        "name": "Diplomatic Immunity",
        "owner_type": "king",
        "category": "protection",
        "rarity": "rare",
        "copies_in_deck": 2,
        "timing": "reactive",
        "effect": {
            "primitive": "block_succession",
            "params": {
                "scope": "next_check_this_round",
                "duration_rounds": 1,
                "trigger": {"type": "succession_imminent"},
            },
        },
        "on_whiff_penalty": {
            "primitive": "gold_loss",
            "params": {"target": "self", "amount": 100},
        },
        "tags": ["protection", "succession"],
        "flavor_text": "The crown does not yield today.",
    },
    {
        "id": "king_extra_audience_001",
        "name": "Extra Audience",
        "owner_type": "king",
        "category": "tempo",
        "rarity": "common",
        "copies_in_deck": 3,
        "timing": "on_reveal",
        "effect": {"primitive": "draw_extra", "params": {"target": "self", "count": 1}},
        "tags": ["tempo"],
        "flavor_text": "Another petition, another card up your sleeve.",
    },
    {
        "id": "king_decree_haste_001",
        "name": "Decree Haste",
        "owner_type": "king",
        "category": "tempo",
        "rarity": "common",
        "copies_in_deck": 2,
        "timing": "on_reveal",
        "effect": {"primitive": "extra_play", "params": {"target": "self", "count": 1}},
        "tags": ["tempo"],
        "flavor_text": "The court moves at royal speed.",
    },
    {
        "id": "king_regal_momentum_001",
        "name": "Regal Momentum",
        "owner_type": "king",
        "category": "tempo",
        "rarity": "rare",
        "copies_in_deck": 2,
        "timing": "on_reveal",
        "effect": {"primitive": "draw_extra", "params": {"target": "self", "count": 2}},
        "tags": ["tempo"],
        "flavor_text": "Momentum favors the throne.",
    },
    {
        "id": "king_spy_master_001",
        "name": "Spy Master",
        "owner_type": "king",
        "category": "information",
        "rarity": "rare",
        "copies_in_deck": 2,
        "timing": "on_reveal",
        "effect": {"primitive": "peek_card", "params": {"target": "target", "card_index": 0}},
        "tags": ["information"],
        "flavor_text": "Eyes everywhere, even in your hand.",
    },
    {
        "id": "king_imperial_edict_001",
        "name": "Imperial Edict",
        "owner_type": "king",
        "category": "supercard",
        "rarity": "supercard",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {
            "primitive": "gold_gain",
            "params": {"target": "self", "amount": 250},
            "secondary_effect": {
                "primitive": "gold_loss",
                "params": {"target": "self", "amount": 100},
            },
        },
        "tags": ["supercard", "economy"],
        "flavor_text": "Absolute power extracts absolute cost.",
        "designer_notes": "High upside with built-in drawback on same reveal.",
    },
]

NEW_NOBLE = [
    {
        "id": "noble_tithe_collectors_001",
        "name": "Tithe Collectors",
        "owner_type": "noble",
        "category": "economy",
        "rarity": "common",
        "copies_in_deck": 3,
        "timing": "on_reveal",
        "effect": {"primitive": "gold_gain", "params": {"target": "self", "amount": 70}},
        "tags": ["economy"],
        "flavor_text": "God's share — and yours.",
    },
    {
        "id": "noble_loan_shark_001",
        "name": "Loan Shark",
        "owner_type": "noble",
        "category": "economy",
        "rarity": "rare",
        "copies_in_deck": 2,
        "timing": "on_reveal",
        "effect": {
            "primitive": "gold_transfer",
            "params": {"from": "target", "to": "self", "amount": 120, "as_theft": True},
        },
        "tags": ["economy"],
        "flavor_text": "Interest due — in gold, not gratitude.",
    },
    {
        "id": "noble_fence_goods_001",
        "name": "Fence Goods",
        "owner_type": "noble",
        "category": "economy",
        "rarity": "common",
        "copies_in_deck": 3,
        "timing": "on_reveal",
        "effect": {
            "primitive": "gold_transfer",
            "params": {"from": "king", "to": "self", "amount": 90, "as_theft": True},
        },
        "tags": ["economy"],
        "flavor_text": "What the crown loses, you gain.",
    },
    {
        "id": "noble_mob_contract_001",
        "name": "Mob Contract",
        "owner_type": "noble",
        "category": "alliance",
        "rarity": "common",
        "copies_in_deck": 3,
        "timing": "on_reveal",
        "effect": {
            "primitive": "alliance_bonus",
            "params": {"amount": 55, "players": ["self", "target"]},
        },
        "tags": ["alliance"],
        "synergy_tags": ["noble_alliance"],
        "flavor_text": "Strength in numbers — for a price.",
    },
    {
        "id": "noble_broken_vow_001",
        "name": "Broken Vow",
        "owner_type": "noble",
        "category": "betrayal",
        "rarity": "common",
        "copies_in_deck": 2,
        "timing": "on_reveal",
        "effect": {
            "primitive": "gold_transfer",
            "params": {"from": "target", "to": "self", "amount": 100, "as_theft": True},
            "secondary_effect": {
                "primitive": "mark_status",
                "params": {"target": "self", "status_name": "oathbreaker", "duration_rounds": 2},
            },
        },
        "requires_state": {"alliance_declared_with_target": True},
        "tags": ["betrayal"],
        "flavor_text": "Promises are for peasants.",
    },
    {
        "id": "noble_backstab_deal_001",
        "name": "Backstab Deal",
        "owner_type": "noble",
        "category": "betrayal",
        "rarity": "rare",
        "copies_in_deck": 2,
        "timing": "on_reveal",
        "effect": {
            "primitive": "gold_transfer",
            "params": {"from": "target", "to": "self", "amount": 180, "as_theft": True},
        },
        "requires_state": {"alliance_declared_with_target": True},
        "tags": ["betrayal"],
        "flavor_text": "The knife was always in the deal.",
    },
    {
        "id": "noble_blackmail_001",
        "name": "Blackmail",
        "owner_type": "noble",
        "category": "disruption",
        "rarity": "common",
        "copies_in_deck": 3,
        "timing": "on_reveal",
        "effect": {
            "primitive": "gold_transfer",
            "params": {"from": "target", "to": "self", "amount": 80, "as_theft": True},
        },
        "tags": ["disruption"],
        "flavor_text": "Pay up, or everyone hears.",
    },
    {
        "id": "noble_public_scandal_001",
        "name": "Public Scandal",
        "owner_type": "noble",
        "category": "disruption",
        "rarity": "common",
        "copies_in_deck": 3,
        "timing": "on_reveal",
        "effect": {
            "primitive": "reveal_hand",
            "params": {"target": "target"},
            "secondary_effect": {
                "primitive": "force_discard",
                "params": {"target": "target", "count": 1},
            },
        },
        "tags": ["disruption", "information"],
        "flavor_text": "Secrets spilled in the square.",
    },
    {
        "id": "noble_embargo_001",
        "name": "Embargo",
        "owner_type": "noble",
        "category": "disruption",
        "rarity": "rare",
        "copies_in_deck": 2,
        "timing": "on_reveal",
        "effect": {
            "primitive": "skip_next_play",
            "params": {"target": "target"},
        },
        "tags": ["disruption"],
        "flavor_text": "Your trade routes are closed.",
    },
    {
        "id": "noble_forged_deeds_001",
        "name": "Forged Deeds",
        "owner_type": "noble",
        "category": "disruption",
        "rarity": "rare",
        "copies_in_deck": 2,
        "timing": "on_reveal",
        "effect": {"primitive": "steal_card", "params": {"from": "target", "to": "self", "count": 1}},
        "tags": ["disruption"],
        "flavor_text": "Paperwork is a weapon.",
    },
    {
        "id": "noble_hidden_cache_001",
        "name": "Hidden Cache",
        "owner_type": "noble",
        "category": "protection",
        "rarity": "common",
        "copies_in_deck": 3,
        "timing": "reactive",
        "effect": {
            "primitive": "protect_gold",
            "params": {
                "target": "self",
                "amount": 100,
                "duration_rounds": 1,
                "specificity": "generic",
                "trigger": {"type": "attacked_this_phase", "target": "self", "attack_type": "gold_theft"},
            },
        },
        "on_whiff_penalty": {
            "primitive": "gold_loss",
            "params": {"target": "self", "amount": 25},
        },
        "tags": ["protection"],
        "synergy_tags": ["noble_defense"],
        "flavor_text": "Coins buried where thieves won't look.",
    },
    {
        "id": "noble_quick_escape_001",
        "name": "Quick Escape",
        "owner_type": "noble",
        "category": "tempo",
        "rarity": "common",
        "copies_in_deck": 3,
        "timing": "on_reveal",
        "effect": {"primitive": "draw_extra", "params": {"target": "self", "count": 1}},
        "tags": ["tempo"],
        "flavor_text": "Leave fast, plan faster.",
    },
    {
        "id": "noble_opportunist_001",
        "name": "Opportunist",
        "owner_type": "noble",
        "category": "tempo",
        "rarity": "common",
        "copies_in_deck": 3,
        "timing": "on_reveal",
        "effect": {"primitive": "extra_play", "params": {"target": "self", "count": 1}},
        "tags": ["tempo"],
        "flavor_text": "Strike while the court blinks.",
    },
    {
        "id": "noble_double_agent_001",
        "name": "Double Agent",
        "owner_type": "noble",
        "category": "tempo",
        "rarity": "rare",
        "copies_in_deck": 2,
        "timing": "on_reveal",
        "effect": {"primitive": "draw_extra", "params": {"target": "self", "count": 2}},
        "tags": ["tempo"],
        "flavor_text": "Two masters, twice the options.",
    },
    {
        "id": "noble_spy_network_001",
        "name": "Spy Network",
        "owner_type": "noble",
        "category": "information",
        "rarity": "common",
        "copies_in_deck": 3,
        "timing": "on_reveal",
        "effect": {"primitive": "peek_card", "params": {"target": "target", "card_index": 0}},
        "tags": ["information"],
        "flavor_text": "Whispers travel faster than horses.",
    },
    {
        "id": "noble_rumor_mill_001",
        "name": "Rumor Mill",
        "owner_type": "noble",
        "category": "information",
        "rarity": "common",
        "copies_in_deck": 3,
        "timing": "on_reveal",
        "effect": {"primitive": "reveal_hand", "params": {"target": "target"}},
        "tags": ["information"],
        "flavor_text": "Truth optional, damage guaranteed.",
    },
    {
        "id": "noble_whisper_campaign_001",
        "name": "Whisper Campaign",
        "owner_type": "noble",
        "category": "information",
        "rarity": "rare",
        "copies_in_deck": 2,
        "timing": "on_reveal",
        "effect": {
            "primitive": "mark_status",
            "params": {"target": "target", "status_name": "discredited", "duration_rounds": 2},
        },
        "tags": ["information"],
        "flavor_text": "Reputation erodes one whisper at a time.",
    },
    {
        "id": "noble_assassins_blade_001",
        "name": "Assassin's Blade",
        "owner_type": "noble",
        "category": "supercard",
        "rarity": "supercard",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {
            "primitive": "gold_transfer",
            "params": {"from": "king", "to": "self", "amount": 300, "as_theft": True},
            "secondary_effect": {
                "primitive": "mark_status",
                "params": {"target": "self", "status_name": "marked", "duration_rounds": 3},
            },
        },
        "tags": ["supercard", "betrayal"],
        "flavor_text": "One cut, one crown closer.",
    },
    {
        "id": "noble_revolution_banner_001",
        "name": "Revolution Banner",
        "owner_type": "noble",
        "category": "supercard",
        "rarity": "supercard",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {
            "primitive": "conditional_swing",
            "params": {
                "condition": {"gold_gt_king": True},
                "effect_if_true": {
                    "primitive": "gold_gain",
                    "params": {"target": "self", "amount": 200},
                },
                "effect_if_false": {
                    "primitive": "gold_loss",
                    "params": {"target": "self", "amount": 150},
                },
            },
        },
        "tags": ["supercard"],
        "flavor_text": "Lead the uprising — or pay for the attempt.",
    },
]


def slug(card: dict) -> str:
    return card["id"].replace("_001", "").split("_", 1)[-1]


def main() -> None:
    for path in (KING / "placeholder.json", NOBLE / "placeholder.json"):
        if path.exists():
            path.unlink()

    for card in NEW_KING:
        out = KING / f"{slug(card)}.json"
        out.write_text(json.dumps(card, indent=2) + "\n", encoding="utf-8")
        print(f"Wrote {out.name}")

    for card in NEW_NOBLE:
        out = NOBLE / f"{slug(card)}.json"
        out.write_text(json.dumps(card, indent=2) + "\n", encoding="utf-8")
        print(f"Wrote {out.name}")

    king_count = len(list(KING.glob("*.json")))
    noble_count = len(list(NOBLE.glob("*.json")))
    print(f"King deck designs: {king_count}, Noble deck designs: {noble_count}, total: {king_count + noble_count}")


if __name__ == "__main__":
    main()
