"""Replace auto-generated stub cards with on-theme designs (PRD §10/§11)."""

from __future__ import annotations

import json
from pathlib import Path

from engine.cards import write_manifest

ROOT = Path(__file__).resolve().parent.parent

STUBS: dict[str, dict] = {
    "cards/king_deck/royal_edict_25.json": {
        "id": "king_royal_edict_25_025",
        "name": "Grain Toll",
        "owner_type": "king",
        "category": "economy",
        "rarity": "common",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {"primitive": "gold_gain", "params": {"target": "self", "amount": 115}},
        "tags": ["economy"],
        "flavor_text": "Every wagon pays the crown before it passes.",
        "designer_notes": "Replaced resize stub; modest King economy (PRD §10).",
    },
    "cards/king_deck/royal_edict_26.json": {
        "id": "king_royal_edict_26_026",
        "name": "Harbor Dues",
        "owner_type": "king",
        "category": "economy",
        "rarity": "common",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {
            "primitive": "gold_transfer",
            "params": {"from": "target", "to": "self", "amount": 62, "as_theft": True},
        },
        "tags": ["economy", "targets_gold"],
        "flavor_text": "The quay master collects — for the throne.",
        "designer_notes": "Replaced resize stub; light King levy on a noble (PRD §10).",
    },
    "cards/king_deck/royal_edict_27.json": {
        "id": "king_royal_edict_27_027",
        "name": "Garrison Inspection",
        "owner_type": "king",
        "category": "disruption",
        "rarity": "common",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {"primitive": "force_discard", "params": {"target": "target", "count": 1}},
        "tags": ["disruption"],
        "flavor_text": "Soldiers toss the saddlebags. Something always falls out.",
        "designer_notes": "Replaced resize stub; King disruption (PRD §10).",
    },
    "cards/king_deck/royal_edict_28.json": {
        "id": "king_royal_edict_28_028",
        "name": "Royal Census",
        "owner_type": "king",
        "category": "information",
        "rarity": "common",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {"primitive": "reveal_hand", "params": {"target": "target"}},
        "tags": ["information"],
        "flavor_text": "Clerks count heads — and hands.",
        "designer_notes": "Replaced resize stub; King information (PRD §10).",
    },
    "cards/king_deck/royal_edict_29.json": {
        "id": "king_royal_edict_29_029",
        "name": "Crown Patronage",
        "owner_type": "king",
        "category": "alliance",
        "rarity": "common",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {
            "primitive": "alliance_bonus",
            "params": {"amount": 68, "players": ["self", "target"]},
        },
        "tags": ["alliance"],
        "synergy_tags": ["king_alliance"],
        "flavor_text": "Favor flows to those who stand beside the throne.",
        "designer_notes": "Replaced resize stub; King alliance payout (PRD §10).",
    },
    "cards/king_deck/royal_edict_30.json": {
        "id": "king_royal_edict_30_030",
        "name": "Vault Seal",
        "owner_type": "king",
        "category": "protection",
        "rarity": "common",
        "copies_in_deck": 1,
        "timing": "reactive",
        "effect": {
            "primitive": "protect_gold",
            "params": {
                "target": "self",
                "amount": 110,
                "duration_rounds": 1,
                "specificity": "generic",
                "trigger": {
                    "type": "attacked_this_phase",
                    "target": "self",
                    "attack_type": "gold_theft",
                },
            },
        },
        "on_whiff_penalty": {"primitive": "gold_loss", "params": {"target": "self", "amount": 5}},
        "tags": ["protection"],
        "synergy_tags": ["king_defense"],
        "flavor_text": "The seal holds — if thieves come knocking.",
        "designer_notes": "Replaced resize stub; King reactive shield with whiff (PRD §10 FR-CARD-4).",
    },
    "cards/noble_deck/court_gambit_31.json": {
        "id": "noble_court_gambit_31_031",
        "name": "Smuggler's Tithe",
        "owner_type": "noble",
        "category": "economy",
        "rarity": "common",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {"primitive": "gold_gain", "params": {"target": "self", "amount": 33}},
        "tags": ["economy"],
        "flavor_text": "What the crown doesn't see, you keep.",
        "designer_notes": "Replaced resize stub; Noble catch-up economy (PRD §10).",
    },
    "cards/noble_deck/court_gambit_32.json": {
        "id": "noble_court_gambit_32_032",
        "name": "Shakedown",
        "owner_type": "noble",
        "category": "betrayal",
        "rarity": "common",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {
            "primitive": "gold_transfer",
            "params": {"from": "target", "to": "self", "amount": 26, "as_theft": True},
        },
        "tags": ["betrayal", "targets_gold"],
        "flavor_text": "Pay up, or explain yourself to the guards.",
        "designer_notes": "Replaced resize stub; Noble theft (PRD §10).",
    },
    "cards/noble_deck/court_gambit_33.json": {
        "id": "noble_court_gambit_33_033",
        "name": "Cut Supply Lines",
        "owner_type": "noble",
        "category": "disruption",
        "rarity": "common",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {"primitive": "force_discard", "params": {"target": "target", "count": 1}},
        "tags": ["disruption"],
        "flavor_text": "No carriages reach the palace tonight.",
        "designer_notes": "Replaced resize stub; Noble disruption via discard (PRD §10).",
    },
    "cards/noble_deck/court_gambit_34.json": {
        "id": "noble_court_gambit_34_034",
        "name": "Stolen Ledger",
        "owner_type": "noble",
        "category": "information",
        "rarity": "common",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {"primitive": "peek_card", "params": {"target": "target", "card_index": 0}},
        "tags": ["information"],
        "flavor_text": "Their secrets are yours for a night.",
        "designer_notes": "Replaced resize stub; Noble information (PRD §10).",
    },
    "cards/noble_deck/court_gambit_35.json": {
        "id": "noble_court_gambit_35_035",
        "name": "Neighborhood Pact",
        "owner_type": "noble",
        "category": "alliance",
        "rarity": "common",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {
            "primitive": "alliance_bonus",
            "params": {"amount": 30, "players": ["self", "target"]},
        },
        "tags": ["alliance"],
        "synergy_tags": ["noble_alliance"],
        "flavor_text": "Your neighbors watch your back — for a share.",
        "designer_notes": "Replaced resize stub; Noble alliance (PRD §10).",
    },
    "cards/noble_deck/court_gambit_36.json": {
        "id": "noble_court_gambit_36_036",
        "name": "Slip Away",
        "owner_type": "noble",
        "category": "tempo",
        "rarity": "common",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {"primitive": "draw_extra", "params": {"target": "self", "count": 1}},
        "tags": ["tempo"],
        "flavor_text": "Leave the hall before the verdict lands.",
        "designer_notes": "Replaced resize stub; Noble tempo (PRD §10).",
    },
    "cards/noble_deck/court_gambit_37.json": {
        "id": "noble_court_gambit_37_037",
        "name": "Hidden Ledger",
        "owner_type": "noble",
        "category": "information",
        "rarity": "common",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {"primitive": "peek_card", "params": {"target": "king", "card_index": 0}},
        "tags": ["information"],
        "flavor_text": "Even kings leave a paper trail.",
        "designer_notes": "Replaced resize stub; Noble information (PRD §10).",
    },
    "cards/noble_deck/court_gambit_38.json": {
        "id": "noble_court_gambit_38_038",
        "name": "Fence the Goods",
        "owner_type": "noble",
        "category": "economy",
        "rarity": "common",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {"primitive": "gold_gain", "params": {"target": "self", "amount": 31}},
        "tags": ["economy"],
        "flavor_text": "A discreet buyer asks no questions.",
        "designer_notes": "Replaced resize stub; Noble economy (PRD §10).",
    },
    "cards/noble_deck/court_gambit_39.json": {
        "id": "noble_court_gambit_39_039",
        "name": "Back-Alley Stab",
        "owner_type": "noble",
        "category": "betrayal",
        "rarity": "common",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {
            "primitive": "gold_transfer",
            "params": {"from": "target", "to": "self", "amount": 20, "as_theft": True},
            "secondary_effect": {
                "primitive": "mark_status",
                "params": {"target": "self", "status_name": "marked", "duration_rounds": 1},
            },
        },
        "tags": ["betrayal"],
        "flavor_text": "The knife is quiet; the debt is not.",
        "designer_notes": "Replaced resize stub; Noble betrayal with cost (PRD §10).",
    },
    "cards/noble_deck/court_gambit_40.json": {
        "id": "noble_court_gambit_40_040",
        "name": "Night Collection",
        "owner_type": "noble",
        "category": "economy",
        "rarity": "common",
        "copies_in_deck": 1,
        "timing": "on_reveal",
        "effect": {"primitive": "gold_gain", "params": {"target": "self", "amount": 28}},
        "tags": ["economy"],
        "flavor_text": "Rent comes due after dark.",
        "designer_notes": "Replaced resize stub; Noble economy (PRD §10).",
    },
}


def main() -> None:
    for rel, card in STUBS.items():
        path = ROOT / rel
        path.write_text(json.dumps(card, indent=2) + "\n", encoding="utf-8")
        print(f"Wrote {path.name}: {card['name']}")
    manifest = write_manifest()
    print(json.dumps({"card_set_version": manifest["version"], "card_count": manifest["card_count"]}, indent=2))


if __name__ == "__main__":
    main()
