FROM node:20-alpine AS build

WORKDIR /app
COPY web/client/package.json web/client/package-lock.json* ./web/client/
RUN cd web/client && npm install

COPY web/client ./web/client
COPY cards ./cards
RUN cd web/client && npm run build

FROM nginx:alpine
COPY web/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/web/client/dist /usr/share/nginx/html
EXPOSE 80
